import "./core/Runtime.js";
import "./audio/AudioManager.js";
import "./world/Map.js";
import "./player/Player.js";
import "./player/Weapons.js";
import "./enemies/Zombie.js";
import "./enemies/Boss.js";
import "./systems/XPSystem.js";
import "./systems/DropSystem.js";
import "./systems/GameState.js";
import "./systems/WaveSystem.js";
import "./systems/SpatialGrid.js";
import "./systems/AISystem.js";
import "./systems/CombatSystem.js";
import "./render/Renderer.js";
import "./core/Input.js";
import "./ui/UI.js";

const G=globalThis;
G.resize();
G.ui.menuPanel.classList.remove("hidden");
requestAnimationFrame(G.loop);
