import "./core/Runtime.js";
import "./core/Constants.js";
import "./audio/AudioManager.js";
import "./world/Biome.js";
import "./world/WorldGenerator.js";
import "./world/WorldCollision.js";
import "./world/Map.js";
import "./player/Player.js";
import "./player/Weapons.js";
import "./enemies/Zombie.js";
import "./enemies/Boss.js";
import "./systems/XPSystem.js";
import "./systems/SaveSystem.js";
import "./systems/CollisionSystem.js";
import "./systems/DNA.js";
import "./systems/EnemyIntro.js";
import "./systems/DropSystem.js";
import "./systems/GameState.js";
import "./systems/WaveSystem.js";
import "./systems/SpatialGrid.js";
import "./systems/AISystem.js";
import "./systems/CombatSystem.js";
import "./systems/Equipment.js";
import "./systems/Skills.js";
import "./systems/Evolution.js";
import "./systems/Achievements.js";
import "./systems/Events.js";
import "./systems/Weather.js";
import "./systems/AdaptiveDirector.js";
import "./player/PlayerProfile.js";
import "./render/Renderer.js?v=9.2.1";
import "./render/CharacterRenderer.js?v=9.2.1";
import "./render/V9Visuals.js?v=9.2.1";
import "./core/Input.js";
import "./ui/UI.js";

const G=globalThis;
G.resize();
G.ui.menuPanel.classList.remove("hidden");
G.renderProfileSummary?.();
requestAnimationFrame(G.loop);
