const G=globalThis;
G.spawnPoint=function(){const side=Math.floor(Math.random()*4),m=75;return side===0?{x:m+Math.random()*(G.WORLD.w-2*m),y:m}:side===1?{x:G.WORLD.w-m,y:m+Math.random()*(G.WORLD.h-2*m)}:side===2?{x:m+Math.random()*(G.WORLD.w-2*m),y:G.WORLD.h-m}:{x:m,y:m+Math.random()*(G.WORLD.h-2*m)}};
const defs={normal:[28,52,105,'#668f6b'],fast:[20,92,75,'#d2a044'],tank:[38,35,300,'#53616b'],exploder:[25,55,95,'#bf6b35'],hunter:[22,120,115,'#9c5a9a'],spitter:[24,48,120,'#4c9b85'],leaper:[23,100,130,'#b58a42'],screamer:[25,58,90,'#a44ca8']};
G.spawnZombie=function(type){const d=defs[type]||defs.normal;let p=G.spawnPoint(),tries=0;while(G.blocked(p.x,p.y,d[0]+3)&&tries++<240)p=G.spawnPoint();if(G.blocked(p.x,p.y,d[0]+3))return false;const elite=G.wave>=6&&Math.random()<Math.min(.14,.045+G.wave*.004);const scale=1+Math.max(0,G.wave-1)*.12;const eliteHp=elite?1.75:1,eliteSpeed=elite?1.12:1,eliteDamage=elite?1.22:1;const hp=d[2]*scale*eliteHp;G.zombies.push({x:p.x,y:p.y,r:d[0]*(elite?1.08:1),speed:d[1]*scale*0+ d[1]*eliteSpeed,damage:d[2]*eliteDamage,hp,maxHp:hp,type,color:d[3],elite,eliteReward:elite?2.2:1,attack:0,burnUntil:0,burnTick:0,stun:0,wander:0,jump:0,strafeDir:1,flash:0,kx:0,ky:0});if(elite)G.showMessage('⚠️ ELITE '+type.toUpperCase(),700);return true};
G.spawnRandomZombie=function(){const r=Math.random();let type=r<.43?'normal':r<.57?'fast':r<.69?'hunter':r<.79?'spitter':r<.87?'tank':r<.92?'leaper':r<.97?'exploder':'screamer';if(G.wave<20&&type==='screamer')type='normal';G.spawnZombie(type)};
G.damageZombie=function(z,n,impact){if(!z||z.hp<=0)return;let crit=false;if(Math.random()<(G.player.critChance||0)){n*=1.75;crit=true}z.hp-=n;G.player.lifeSteal&&(G.player.hp=Math.min(G.player.maxHp,G.player.hp+G.player.lifeSteal*.15));z.flash=110;z.stun=Math.max(z.stun||0,crit?100:55);G.shake=Math.max(G.shake,crit?3.2:1.0);for(let i=0;i<(crit?7:3);i++){const a=(impact?.angle??Math.random()*Math.PI*2)+(Math.random()-.5)*1.2,s=(crit?110:70)+Math.random()*80;G.particles.push({x:z.x,y:z.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:crit?300:220,color:crit?'#ffd45a':'#d8e1dc',size:crit?3+Math.random()*3:2+Math.random()*2})}if(impact){const k=impact.knockback||0;z.kx=(z.kx||0)+Math.cos(impact.angle)*k;z.ky=(z.ky||0)+Math.sin(impact.angle)*k}G.playSound('hit');G.texts.push({x:z.x,y:z.y-z.r-8,t:Math.round(n),life:crit?520:420,color:crit?'#ffd45a':'#fff',crit});if(crit)G.texts.push({x:z.x,y:z.y-z.r-28,t:'CRIT!',life:480,color:'#ffd45a',critLabel:true});if(z.hp<=0)G.killZombie(z)};
G.killZombie=function(z){if(z._dead)return;z._dead=true;z.hp=0;G.kills++;G.totalKills++;G.combo=(G.combo||0)+1;G.comboTimer=3500;G.statsMeta&&(G.statsMeta.kills=G.totalKills);G.score+=Math.floor((100+Math.min(200,G.combo*4))*(z.eliteReward||1));G.coins+=Math.floor((6+Math.random()*8)*(1+(G.getDNAUpgrade?.('coins')||0)*.05)*(G.player.coinBoost||1)*(G.currentEvent?.[0]==='bounty'?1.5:1)*(z.eliteReward||1));G.waveKills++;G.gainXP((20+(z.type==='tank'?20:0))*(z.eliteReward||1));G.addWeaponXP?.(G.selectedWeapon,1);if(z.lastDamageSource==='fire')G.metaAdd?.('fire',1);if(z.lastDamageSource==='grenade')G.metaAdd?.('grenade',1);if(G.combo>=20)G.metaAdd?.('combo',G.combo);if(z.type==='screamer')G.metaAdd?.('screamer',1);if(G.player.lifeSteal)G.player.hp=Math.min(G.player.maxHp,G.player.hp+G.player.lifeSteal);if(z.type==='fire')G.metaAdd?.('fire',1);if(Math.random()<(0.18*(1+(G.getDNAUpgrade?.('drop')||0)*.05))){const types=['hp','grenade','coin','ammo'];G.drops.push({x:z.x,y:z.y,type:types[Math.floor(Math.random()*types.length)],life:15000})}if(Math.random()<.025)G.powerups.push({x:z.x,y:z.y,type:['rage','freeze','heal','insta'][Math.floor(Math.random()*4)],life:12000});const burstCount=z.elite?26:(z.type==='tank'?18:14);for(let i=0;i<burstCount;i++){const a=Math.random()*Math.PI*2,s=80+Math.random()*220;G.particles.push({x:z.x,y:z.y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:420+Math.random()*180,color:z.type==='exploder'?'#ff7a30':(critKillColor(z.type)),size:2+Math.random()*4})}function critKillColor(type){return type==='screamer'?'#d96cff':type==='tank'?'#aeb9c0':type==='spitter'?'#67d9b8':'#8b302f'}if(z.elite){for(let i=0;i<12;i++){const a=Math.random()*Math.PI*2;G.particles.push({x:z.x,y:z.y,vx:Math.cos(a)*(120+Math.random()*160),vy:Math.sin(a)*(120+Math.random()*160),life:650,color:'#ffcf4a',size:2+Math.random()*3})}G.showMessage('⭐ ELITE DEFEATED · BONUS LOOT',900)}if(z.type==='exploder')G.areaDamage(z.x,z.y,100,45*G.player.damage,'player')};
G.updateZombies=function(dt){const now=performance.now();G.updatePathField?.(dt);for(const z of G.zombies){if(z.hp<=0)continue;if(z.flash>0)z.flash-=dt;if(z.burnUntil>now){z.burnTick-=dt;if(z.burnTick<=0){G.damageZombie(z,2.5*G.player.damage*G.player.burnBoost);z.burnTick=600}}if(z.hp<=0)continue;z.stun=Math.max(0,z.stun-dt);z.attack=Math.max(0,z.attack-dt);z.jump=Math.max(0,z.jump-dt);
  // Weapon impact knockback decays quickly, while normal AI movement remains in control.
  if(Math.abs(z.kx)+Math.abs(z.ky)>0.5){G.moveEntity(z,z.kx,z.ky,dt/1000);const decay=Math.pow(z.type==='tank'?.08:.035,dt/1000);z.kx*=decay;z.ky*=decay}else{z.kx=0;z.ky=0}
  const dx=G.player.x-z.x,dy=G.player.y-z.y,d=Math.hypot(dx,dy)||1;
  if(z.type==='screamer'){if(d<300)G.aiPathMove(z,z.x-dx/d*80,z.y-dy/d*80,Math.min(z.speed,42),dt);else if(d>500)G.aiPathMove(z,G.player.x,G.player.y,z.speed,dt);if(z.attack<=0){z.attack=2200;for(const q of G.spatialGrid.near(z.x,z.y,240)){if(q!==z&&q.hp>0)q.buffUntil=now+1800}}continue}
  if(z.type==='spitter'){if(d<300)G.aiPathMove(z,z.x-dx/d*120,z.y-dy/d*120,Math.min(z.speed,38),dt);else if(d>520)G.aiPathMove(z,G.player.x,G.player.y,z.speed,dt);if(d<520&&d>220&&z.attack<=0){z.attack=1550;G.enemyShot(z)}continue}
  let tx=G.player.x,ty=G.player.y,sp=z.speed;if(z.type==='leaper'&&d<360&&z.jump<=0){z.jump=1900;z._leapX=G.player.x;z._leapY=G.player.y}if(z.type==='leaper'&&z.jump>0&&z.jump<1500){tx=z._leapX;ty=z._leapY;sp=230}
  if(z.buffUntil&&z.buffUntil>now)sp*=1.22;if(z.stun<=0){const near=G.spatialGrid.near(z.x,z.y,80),sep=G.aiSeparation(z,near),sd=Math.hypot(sep[0],sep[1]);if(sd>1){tx+=sep[0]*.65;ty+=sep[1]*.65}if(z.type==='hunter'&&d<260){const side=z.strafeDir||1;tx+=(-dy/d)*120*side;ty+=(dx/d)*120*side}G.aiPathMove(z,tx,ty,sp,dt)}
  if(d<z.r+G.player.r+3&&z.attack<=0&&z.type!=='spitter'){G.damagePlayer(z.damage*(z.type==='exploder'?.15:.04));z.attack=700;if(z.type==='exploder'){G.areaDamage(z.x,z.y,100,30,'player');z.hp=0;z._dead=true}}
 }
 let w=0;for(let i=0;i<G.zombies.length;i++){const z=G.zombies[i];if(z.hp>0)G.zombies[w++]=z}G.zombies.length=w};
G.enemyShot=function(z){const a=Math.atan2(G.player.y-z.y,G.player.x-z.x);G.bullets.push({x:z.x+Math.cos(a)*z.r,y:z.y+Math.sin(a)*z.r,vx:Math.cos(a)*320,vy:Math.sin(a)*320,life:1600,damage:12,type:'enemy',pierce:1,hit:new Set(),owner:z})};
