const G=globalThis;
G.spawnPoint=function(){const side=Math.floor(Math.random()*4),m=75;return side===0?{x:m+Math.random()*(G.WORLD.w-2*m),y:m}:side===1?{x:G.WORLD.w-m,y:m+Math.random()*(G.WORLD.h-2*m)}:side===2?{x:m+Math.random()*(G.WORLD.w-2*m),y:G.WORLD.h-m}:{x:m,y:m+Math.random()*(G.WORLD.h-2*m)}};
G.blocked=function(x,y,r){if(x<r+15||y<r+15||x>G.WORLD.w-r-15||y>G.WORLD.h-r-15)return true;for(const a of G.walls)if(x+r>a.x&&x-r<a.x+a.w&&y+r>a.y&&y-r<a.y+a.h)return true;return false};
G.moveEntity=function(o,vx,vy,dt){const nx=o.x+vx*dt,ny=o.y+vy*dt;if(!G.blocked(nx,o.y,o.r))o.x=nx;if(!G.blocked(o.x,ny,o.r))o.y=ny};
const defs={normal:[28,52,105,'#668f6b'],fast:[20,92,75,'#d2a044'],tank:[38,35,300,'#53616b'],exploder:[25,55,95,'#bf6b35'],hunter:[22,120,115,'#9c5a9a'],spitter:[24,48,120,'#4c9b85'],leaper:[23,100,130,'#b58a42']};
G.spawnZombie=function(type){let p=G.spawnPoint(),tries=0;while(G.blocked(p.x,p.y,22)&&tries++<20)p=G.spawnPoint();const d=defs[type]||defs.normal,hp=d[2]*(1+Math.max(0,G.wave-1)*.12);G.zombies.push({x:p.x,y:p.y,r:d[0],speed:d[1],damage:d[2],hp,maxHp:hp,type,color:d[3],attack:0,burnUntil:0,burnTick:0,stun:0,wander:0,jump:0,strafeDir:1,flash:0})};
G.spawnRandomZombie=function(){const r=Math.random(),type=r<.48?'normal':r<.65?'fast':r<.77?'hunter':r<.86?'spitter':r<.93?'tank':r<.97?'leaper':'exploder';G.spawnZombie(type)};
G.damageZombie=function(z,n){if(!z||z.hp<=0)return;z.hp-=n;z.flash=90;z.stun=Math.max(z.stun||0,55);G.shake=Math.max(G.shake,.8);G.playSound('hit');G.texts.push({x:z.x,y:z.y-z.r-8,t:Math.round(n),life:420,color:'#fff'});if(z.hp<=0)G.killZombie(z)};
G.killZombie=function(z){if(z._dead)return;z._dead=true;z.hp=0;G.kills++;G.totalKills++;G.score+=100;G.coins+=Math.floor(6+Math.random()*8);G.waveKills++;G.gainXP(20+(z.type==='tank'?20:0));if(Math.random()<.18){const types=['hp','grenade','coin','ammo'];G.drops.push({x:z.x,y:z.y,type:types[Math.floor(Math.random()*types.length)],life:15000})}if(Math.random()<.025)G.powerups.push({x:z.x,y:z.y,type:['rage','freeze','heal','insta'][Math.floor(Math.random()*4)],life:12000});for(let i=0;i<12;i++)G.particles.push({x:z.x,y:z.y,vx:(Math.random()-.5)*180,vy:(Math.random()-.5)*180,life:400,color:z.type==='exploder'?'#ff7a30':'#8b302f',size:2+Math.random()*4});if(z.type==='exploder')G.areaDamage(z.x,z.y,100,45*G.player.damage,'player')};
G.updateZombies=function(dt){const now=performance.now();for(const z of G.zombies){if(z.hp<=0)continue;if(z.flash>0)z.flash-=dt;if(z.burnUntil>now){z.burnTick-=dt;if(z.burnTick<=0){G.damageZombie(z,2.5*G.player.damage*G.player.burnBoost);z.burnTick=600}}if(z.hp<=0)continue;z.stun=Math.max(0,z.stun-dt);z.attack=Math.max(0,z.attack-dt);z.jump=Math.max(0,z.jump-dt);const dx=G.player.x-z.x,dy=G.player.y-z.y,d=Math.hypot(dx,dy)||1;
  // Spitter keeps distance and fires only at the player; no friendly/self damage.
  if(z.type==='spitter'){if(d<300)G.aiMoveToward(z,z.x-dx/d*120,z.y-dy/d*120,Math.min(z.speed,38),dt);else if(d>520)G.aiMoveToward(z,G.player.x,G.player.y,z.speed,dt);if(d<520&&d>220&&z.attack<=0){z.attack=1550;G.enemyShot(z)}continue}
  // Leaper periodically commits to the player's current position, then returns to pursuit.
  let tx=G.player.x,ty=G.player.y,sp=z.speed;if(z.type==='leaper'&&d<360&&z.jump<=0){z.jump=1900;z._leapX=G.player.x;z._leapY=G.player.y}if(z.type==='leaper'&&z.jump>0&&z.jump<1500){tx=z._leapX;ty=z._leapY;sp=230}
  if(z.stun<=0){const near=G.spatialGrid.near(z.x,z.y,80),sep=G.aiSeparation(z,near),sd=Math.hypot(sep[0],sep[1]);if(sd>1){tx+=sep[0]*.65;ty+=sep[1]*.65}if(z.type==='hunter'&&d<260){const side=z.strafeDir||1;tx+=(-dy/d)*120*side;ty+=(dx/d)*120*side}G.aiMoveToward(z,tx,ty,sp,dt)}
  if(d<z.r+G.player.r+3&&z.attack<=0&&z.type!=='spitter'){G.damagePlayer(z.damage*(z.type==='exploder'?.15:.04));z.attack=700;if(z.type==='exploder'){G.areaDamage(z.x,z.y,100,30,'player');z.hp=0;z._dead=true}}
 }
 let w=0;for(let i=0;i<G.zombies.length;i++){const z=G.zombies[i];if(z.hp>0)G.zombies[w++]=z}G.zombies.length=w};
G.enemyShot=function(z){const a=Math.atan2(G.player.y-z.y,G.player.x-z.x);G.bullets.push({x:z.x+Math.cos(a)*z.r,y:z.y+Math.sin(a)*z.r,vx:Math.cos(a)*320,vy:Math.sin(a)*320,life:1600,damage:12,type:'enemy',pierce:1,hit:new Set(),owner:z})};
