// Auto-split from Zombie Outbreak V3.1. Gameplay intentionally unchanged in this refactor.
const G = globalThis;

G.draw = function(){G.ctx.clearRect(0,0,G.W,G.H);G.ctx.fillStyle='#0a1510';G.ctx.fillRect(0,0,G.W,G.H);G.ctx.save();if(G.state==='playing'&&G.mouse.down&&G.selectedWeapon===4&&G.owned[4])G.drawFlameCone();let sx=(Math.random()-.5)*G.shake,sy=(Math.random()-.5)*G.shake;G.ctx.translate(-G.camera.x+sx,-G.camera.y+sy);G.drawWorld();G.drawDrops();G.drawPowerups();for(const g of G.grenades)G.drawGrenade(g);for(const b of G.bullets)G.drawBullet(b);for(const z of G.zombies)G.drawZombie(z);if(G.boss)G.drawBoss();G.drawPlayer();G.drawParticles();G.drawTexts();G.ctx.restore();G.drawVignette();G.updateUI()};

G.drawWorld=function(){
 if(!G.worldCache){const c=document.createElement('canvas');c.width=G.WORLD.w;c.height=G.WORLD.h;const x=c.getContext('2d');x.fillStyle='#122019';x.fillRect(0,0,c.width,c.height);x.strokeStyle='#263d32';x.lineWidth=2;for(let xx=0;xx<G.WORLD.w;xx+=80){x.beginPath();x.moveTo(xx,0);x.lineTo(xx,G.WORLD.h);x.stroke()}for(let yy=0;yy<G.WORLD.h;yy+=80){x.beginPath();x.moveTo(0,yy);x.lineTo(G.WORLD.w,yy);x.stroke()}for(const a of G.walls){x.fillStyle='#303b37';x.fillRect(a.x,a.y,a.w,a.h);x.fillStyle='#46534e';x.fillRect(a.x+5,a.y+5,a.w-10,8);x.strokeStyle='#151d19';x.strokeRect(a.x,a.y,a.w,a.h)}G.worldCache=c}
 G.ctx.drawImage(G.worldCache,0,0);
};

G.drawFlameCone=function(){
  const a=G.aim(),now=performance.now();G.ctx.save();G.ctx.lineCap='round';
  // Outer heat cone
  G.ctx.globalAlpha=.12;G.ctx.fillStyle='#ff5a18';G.ctx.beginPath();G.ctx.moveTo(G.player.x,G.player.y);G.ctx.arc(G.player.x,G.player.y,345,a-.48,a+.48);G.ctx.closePath();G.ctx.fill();
  G.ctx.globalAlpha=.18;G.ctx.fillStyle='#ff9d2e';G.ctx.beginPath();G.ctx.moveTo(G.player.x,G.player.y);G.ctx.arc(G.player.x,G.player.y,285,a-.34,a+.34);G.ctx.closePath();G.ctx.fill();
  // Animated flame tongues
  for(let i=0;i<9;i++){const t=i/8;const ang=a+Math.sin(now*.012+i*2.7)*.055+(Math.random()-.5)*.035;const len=55+t*230;const sx=G.player.x+Math.cos(a)*24,sy=G.player.y+Math.sin(a)*24;const ex=sx+Math.cos(ang)*len,ey=sy+Math.sin(ang)*len;G.ctx.globalAlpha=.34*(1-t*.55);G.ctx.strokeStyle=i%3===0?'#fff1a0':i%2?'#ffb52e':'#ff6b18';G.ctx.lineWidth=7-t*4;G.ctx.beginPath();G.ctx.moveTo(sx,sy);G.ctx.quadraticCurveTo((sx+ex)/2+Math.sin(now*.01+i)*18,(sy+ey)/2-Math.cos(now*.01+i)*18,ex,ey);G.ctx.stroke();}
  G.ctx.restore();
};

G.drawPlayer = function(){const a=G.aim(),moving=G.keys.has('w')||G.keys.has('a')||G.keys.has('s')||G.keys.has('d')||G.keys.has('arrowup')||G.keys.has('arrowdown')||G.keys.has('arrowleft')||G.keys.has('arrowright'),t=performance.now()/100;G.ctx.save();G.ctx.translate(G.player.x,G.player.y);G.ctx.rotate(a);G.ctx.globalAlpha=G.invuln>0&&Math.floor(G.invuln/70)%2===0?.45:1;G.ctx.fillStyle='#0008';G.ctx.beginPath();G.ctx.ellipse(0,18,20,8,0,0,Math.PI*2);G.ctx.fill();let leg=Math.sin(t*2.4)*(moving?6:1);G.ctx.strokeStyle='#18232a';G.ctx.lineWidth=7;G.ctx.lineCap='round';G.ctx.beginPath();G.ctx.moveTo(-7,8);G.ctx.lineTo(-8+leg,23);G.ctx.moveTo(7,8);G.ctx.lineTo(8-leg,23);G.ctx.stroke();G.ctx.fillStyle='#536a82';G.ctx.fillRect(-11,-4,22,19);G.ctx.fillStyle='#e2b08b';G.ctx.beginPath();G.ctx.arc(0,-16,10,0,Math.PI*2);G.ctx.fill();G.ctx.fillStyle='#3a2c28';G.ctx.beginPath();G.ctx.arc(0,-20,10,Math.PI,Math.PI*2);G.ctx.fill();G.ctx.strokeStyle='#e2b08b';G.ctx.lineWidth=5;G.ctx.beginPath();G.ctx.moveTo(6,-1);G.ctx.lineTo(17,4);G.ctx.stroke();G.ctx.fillStyle='#252a2b';const gunRecoil=G.player.recoil;G.ctx.fillRect(14-gunRecoil,1,30,6);G.ctx.fillStyle='#d4d9d5';G.ctx.fillRect(40-gunRecoil,1,7,6);if(G.player.muzzle>0){G.ctx.globalAlpha=G.player.muzzle/90;G.ctx.fillStyle=G.weapons[G.selectedWeapon]?.color||'#ffd36b';G.ctx.beginPath();G.ctx.arc(50-gunRecoil,4,8+Math.random()*5,0,Math.PI*2);G.ctx.fill();G.ctx.globalAlpha=1}G.ctx.restore();if(G.attackTimer>250){G.ctx.save();G.ctx.translate(G.player.x,G.player.y);G.ctx.rotate(a);G.ctx.strokeStyle='#f6e2a4';G.ctx.lineWidth=6;G.ctx.beginPath();G.ctx.arc(20,0,65,-.8,.8);G.ctx.stroke();G.ctx.restore()}};

G.drawZombie = function(z){if(z.x<G.camera.x-80||z.x>G.camera.x+G.W+80||z.y<G.camera.y-80||z.y>G.camera.y+G.H+80)return;G.ctx.save();G.ctx.translate(z.x,z.y);const moving=performance.now()/100;G.ctx.fillStyle='#0007';G.ctx.beginPath();G.ctx.ellipse(0,z.r*.75,z.r*.8,z.r*.3,0,0,Math.PI*2);G.ctx.fill();G.ctx.strokeStyle='#1c2a23';G.ctx.lineWidth=5;G.ctx.beginPath();G.ctx.moveTo(-z.r*.35,z.r*.45);G.ctx.lineTo(-z.r*.55,z.r*.9);G.ctx.moveTo(z.r*.35,z.r*.45);G.ctx.lineTo(z.r*.55,z.r*.9);G.ctx.stroke();G.ctx.fillStyle=z.color;G.ctx.fillRect(-z.r*.65,-z.r*.25,z.r*1.3,z.r*1.1);G.ctx.fillStyle='#7c9b78';G.ctx.beginPath();G.ctx.arc(0,-z.r*.55,z.r*.62,0,Math.PI*2);G.ctx.fill();G.ctx.fillStyle='#382d25';G.ctx.beginPath();G.ctx.arc(0,-z.r*.8,z.r*.6,Math.PI,Math.PI*2);G.ctx.fill();G.ctx.strokeStyle='#7c9b78';G.ctx.lineWidth=5;G.ctx.beginPath();G.ctx.moveTo(-z.r*.55,0);G.ctx.lineTo(-z.r*.95,10+Math.sin(moving)*4);G.ctx.moveTo(z.r*.55,0);G.ctx.lineTo(z.r*.95,10-Math.sin(moving)*4);G.ctx.stroke();G.ctx.fillStyle='#e33';G.ctx.beginPath();G.ctx.arc(-z.r*.22,-z.r*.62,2.8,0,Math.PI*2);G.ctx.arc(z.r*.22,-z.r*.62,2.8,0,Math.PI*2);G.ctx.fill();if(z.type==='tank'){G.ctx.strokeStyle='#98a7b2';G.ctx.lineWidth=5;G.ctx.strokeRect(-z.r*.7,-z.r*.15,z.r*1.4,z.r*.85)}if(z.type==='spitter'){G.ctx.fillStyle='#65e5a5';G.ctx.beginPath();G.ctx.arc(0,-z.r*.2,6,0,Math.PI*2);G.ctx.fill()}if(z.type==='leaper'){G.ctx.strokeStyle='#f3c75f';G.ctx.setLineDash([4,4]);G.ctx.beginPath();G.ctx.arc(0,0,z.r+6,0,Math.PI*2);G.ctx.stroke();G.ctx.setLineDash([])}if(z.type==='exploder'){G.ctx.strokeStyle='#ff7438';G.ctx.lineWidth=3;G.ctx.beginPath();G.ctx.arc(0,0,z.r+7,0,Math.PI*2);G.ctx.stroke()}if(z.type==='screamer'){G.ctx.strokeStyle='#e889ff';G.ctx.lineWidth=3;G.ctx.beginPath();G.ctx.arc(0,-z.r*.25,7,0,Math.PI*2);G.ctx.stroke();G.ctx.beginPath();G.ctx.arc(0,-z.r*.25,13,0,Math.PI*2);G.ctx.stroke();}G.ctx.restore();if(z.hp<z.maxHp){G.ctx.fillStyle='#1c2722';G.ctx.fillRect(z.x-z.r,z.y-z.r-17,z.r*2,4);G.ctx.fillStyle='#e25353';G.ctx.fillRect(z.x-z.r,z.y-z.r-17,z.r*2*Math.max(0,z.hp/z.maxHp),4)}};

G.drawBoss = function(){G.ctx.save();G.ctx.translate(G.boss.x,G.boss.y);G.ctx.fillStyle='#0009';G.ctx.beginPath();G.ctx.ellipse(0,50,65,22,0,0,Math.PI*2);G.ctx.fill();G.ctx.fillStyle=G.boss.flash>0?'#fff':G.boss.phase===3?'#9e2222':'#5b3035';G.ctx.beginPath();G.ctx.arc(0,0,G.boss.r,0,Math.PI*2);G.ctx.fill();G.ctx.strokeStyle='#e1b84d';G.ctx.lineWidth=6;G.ctx.beginPath();G.ctx.moveTo(-30,-35);G.ctx.lineTo(-20,-75);G.ctx.lineTo(-5,-48);G.ctx.lineTo(12,-78);G.ctx.lineTo(28,-34);G.ctx.stroke();G.ctx.fillStyle='#ffdd55';G.ctx.beginPath();G.ctx.arc(-20,-12,6,0,Math.PI*2);G.ctx.arc(20,-12,6,0,Math.PI*2);G.ctx.fill();G.ctx.strokeStyle='#f16b4f';G.ctx.lineWidth=7;G.ctx.beginPath();G.ctx.moveTo(-45,5);G.ctx.lineTo(-75,30);G.ctx.moveTo(45,5);G.ctx.lineTo(75,30);G.ctx.stroke();G.ctx.restore();G.ctx.fillStyle='#1c2722';G.ctx.fillRect(G.boss.x-75,G.boss.y-G.boss.r-25,150,10);G.ctx.fillStyle=G.boss.phase===3?'#f23a3a':'#c33b48';G.ctx.fillRect(G.boss.x-75,G.boss.y-G.boss.r-25,150*Math.max(0,G.boss.hp/G.boss.maxHp),10);G.ctx.fillStyle='#fff';G.ctx.textAlign='center';G.ctx.font='bold 15px Arial';G.ctx.fillText('👑 BOSS · PHASE '+G.boss.phase,G.boss.x,G.boss.y-G.boss.r-32)};

G.drawBullet = function(b){if(b.x<G.camera.x-30||b.x>G.camera.x+G.W+30||b.y<G.camera.y-30||b.y>G.camera.y+G.H+30)return;G.ctx.fillStyle=b.type==='enemy'?'#ff675c':(G.weapons[b.type]?.color||'#fff');G.ctx.beginPath();G.ctx.arc(b.x,b.y,b.type===5?4:3,0,Math.PI*2);G.ctx.fill()};

G.drawGrenade = function(g){if(g.x<G.camera.x-30||g.x>G.camera.x+G.W+30||g.y<G.camera.y-30||g.y>G.camera.y+G.H+30)return;G.ctx.fillStyle='#25362c';G.ctx.beginPath();G.ctx.arc(g.x,g.y,8,0,Math.PI*2);G.ctx.fill();G.ctx.fillStyle='#d9c28b';G.ctx.fillRect(g.x-2,g.y-11,4,4)};

G.drawDrops = function(){for(const d of G.drops){if(d.x<G.camera.x-40||d.x>G.camera.x+G.W+40||d.y<G.camera.y-40||d.y>G.camera.y+G.H+40)continue;const bob=Math.sin(performance.now()/160+d.x)*4;G.ctx.save();G.ctx.translate(d.x,d.y+bob);G.ctx.fillStyle='#0007';G.ctx.beginPath();G.ctx.ellipse(0,12,15,6,0,0,Math.PI*2);G.ctx.fill();if(d.type==='hp'){G.ctx.fillStyle='#e8eee9';G.ctx.fillRect(-12,-10,24,22);G.ctx.fillStyle='#d53f4c';G.ctx.fillRect(-4,-8,8,18);G.ctx.fillRect(-9,-3,18,8)}if(d.type==='ammo'){G.ctx.fillStyle='#c99d4d';G.ctx.fillRect(-13,-10,26,20);G.ctx.fillStyle='#55422a';for(let i=-8;i<=8;i+=8)G.ctx.fillRect(i,-7,4,14)}if(d.type==='grenade'){G.ctx.fillStyle='#3f5746';G.ctx.beginPath();G.ctx.arc(0,2,10,0,Math.PI*2);G.ctx.fill();G.ctx.fillStyle='#d6c185';G.ctx.fillRect(-2,-12,4,5)}if(d.type==='coin'){G.ctx.fillStyle='#f3c64f';G.ctx.beginPath();G.ctx.arc(0,0,11,0,Math.PI*2);G.ctx.fill();G.ctx.fillStyle='#9a6c1f';G.ctx.font='bold 12px Arial';G.ctx.textAlign='center';G.ctx.fillText('$',0,4)}G.ctx.restore()}};

G.drawPowerups = function(){for(const p of G.powerups){if(p.x<G.camera.x-40||p.x>G.camera.x+G.W+40||p.y<G.camera.y-40||p.y>G.camera.y+G.H+40)continue;const y=p.y+Math.sin(performance.now()/180)*5;G.ctx.save();G.ctx.translate(p.x,y);G.ctx.fillStyle=p.type==='rage'?'#f05':p.type==='freeze'?'#61cfff':p.type==='heal'?'#68df85':'#ffd34e';G.ctx.beginPath();G.ctx.arc(0,0,14,0,Math.PI*2);G.ctx.fill();G.ctx.fillStyle='#07100d';G.ctx.font='bold 13px Arial';G.ctx.textAlign='center';G.ctx.textBaseline='middle';G.ctx.fillText(p.type==='rage'?'R':p.type==='freeze'?'F':p.type==='heal'?'+':'K',0,0);G.ctx.restore()}};

G.drawParticles = function(){for(const p of G.particles){if(p.x<G.camera.x-20||p.x>G.camera.x+G.W+20||p.y<G.camera.y-20||p.y>G.camera.y+G.H+20)continue;G.ctx.globalAlpha=Math.max(0,p.life/600);G.ctx.fillStyle=p.color;G.ctx.beginPath();G.ctx.arc(p.x,p.y,p.size,0,Math.PI*2);G.ctx.fill()}G.ctx.globalAlpha=1};

G.drawTexts = function(){G.ctx.textAlign='center';G.ctx.font='bold 14px Arial';for(const t of G.texts){if(t.x<G.camera.x-40||t.x>G.camera.x+G.W+40||t.y<G.camera.y-40||t.y>G.camera.y+G.H+40)continue;G.ctx.globalAlpha=Math.max(0,t.life/520);G.ctx.fillStyle=t.color;G.ctx.fillText(t.t,t.x,t.y)}G.ctx.globalAlpha=1};

G.drawVignette = function(){if(!G.vignette||G.vignetteW!==G.W||G.vignetteH!==G.H){const c=document.createElement('canvas');c.width=Math.max(1,Math.floor(G.W));c.height=Math.max(1,Math.floor(G.H));const x=c.getContext('2d');const g=x.createRadialGradient(G.W/2,G.H/2,Math.min(G.W,G.H)*.25,G.W/2,G.H/2,Math.max(G.W,G.H)*.7);g.addColorStop(0,'transparent');g.addColorStop(1,'#0009');x.fillStyle=g;x.fillRect(0,0,G.W,G.H);G.vignette=c;G.vignetteW=G.W;G.vignetteH=G.H;}G.ctx.drawImage(G.vignette,0,0)};

G.updateUI = function(){
  G.uiTick+=16.67;
  if(G.uiTick<G.uiInterval)return;
  G.uiTick=0;
  const hp=Math.ceil(G.player.hp), w=G.selectedWeapon, maxMag=G.player.maxMag[w], mag=G.player.mag[w];
  G.ui.hpText.textContent=hp+' / '+G.player.maxHp;
  G.ui.hpBar.style.width=Math.max(0,hp/G.player.maxHp*100)+'%';
  G.ui.xpText.textContent=Math.floor(G.xp)+' / '+G.xpNeed;
  G.ui.xpBar.style.width=(G.xp/G.xpNeed*100)+'%';
  G.ui.stats.textContent='🌊 Wave '+G.wave+' · ☠️ '+G.waveKills+'/'+G.waveTotal+' · ⭐ Lv.'+G.level+' · 💰 '+G.coins+' · 🧬 '+G.dna+' · 🏆 '+G.score;
  G.ui.weaponText.textContent='🔫 '+G.weapons[w].name+' ['+w+']';
  G.ui.ammoText.innerHTML='弹匣 '+mag+'/'+maxMag+((w===3||w===5)?' · '+G.player.reserve[w]+' reserve':'')+(G.reloadTimer>0?' <span class="reloadBadge">↻ RELOADING</span>':'');
  G.ui.dashText.textContent='⚡ Dash '+(G.player.dashCooldown>0?Math.ceil(G.player.dashCooldown/1000)+'s':'READY');
  G.ui.grenadeText.textContent='💣 '+G.player.grenades+' · Space 近战';
};
